SELECT ROUTINE_NAME AS "LIST OF CREATE PROCEDURE"
FROM information_schema.ROUTINES 
WHERE ROUTINE_TYPE = 'PROCEDURE' 
  AND ROUTINE_SCHEMA = 'appolo';
  

CREATE VIEW listp AS
SELECT ROUTINE_NAME AS "LIST OF CREATE PROCEDURE"
FROM information_schema.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE'
  AND ROUTINE_SCHEMA = 'appolo';
  
  
SELECT * FROM listp;  
